services:
  surrealdb:
    env_file:
      - .env
    entrypoint:
      - /surreal
      - start
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
    image: surrealdb/surrealdb:v2.1.4
    ports:
      - 8000:8000
  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - 5672:5672
      - 15672:15672
  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
  backend:
    depends_on:
      - surrealdb
      - rabbitmq
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
