services:
  init-data:
    image: busybox
    command: chmod -R 777 /data
    volumes:
      - surrealdb-data:/data

  surrealdb:
    depends_on:
      - init-data
    env_file:
      - .env
    entrypoint:
      - /surreal
      - start
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - rocksdb:/data/finanalize.db
    image: surrealdb/surrealdb:v2.1.4
    ports:
      - 8000:8000
    volumes:
      - surrealdb-data:/data

  rabbitmq:
    image: rabbitmq:4.0-management
    ports:
      - 5672:5672
      - 15672:15672

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173

  backend:
    depends_on:
      - surrealdb
      - rabbitmq
      - searxng
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    environment:
      - BASE_URL=http://localhost:8081/
    ports:
      - 8081:8080
    volumes:
      - searxng-data:/etc/searxng

volumes:
  surrealdb-data:
  searxng-data:
