services:
  init-data:
    container_name: init
    image: busybox
    command: chmod -R 777 /data
    volumes:
      - surrealdb-data:/data

  surrealdb:
    container_name: surrealdb
    depends_on:
      - init-data
    env_file:
      - .env
    entrypoint:
      - /surreal
      - start
      - --user
      - $DB_USER
      - --pass
      - $DB_PASSWORD
      - rocksdb:/data/finanalize.db
    image: surrealdb/surrealdb:v2.1.4
    ports:
      - 8000:8000
    volumes:
      - surrealdb-data:/data

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.0-management
    ports:
      - 5672:5672
      - 15672:15672

  frontend:
    container_name: frontend
    depends_on:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173

  backend:
    container_name: backend
    depends_on:
      - surrealdb
      - rabbitmq
      - searxng
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    env_file: ".env"

  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    environment:
      - BASE_URL=http://localhost:8081/
    ports:
      - 8081:8080
    volumes:
      - ./searxng:/etc/searxng

  ullm:
    container_name: ullm
    build: https://github.com/norpie/uLLM-API.git#main
    ports:
      - 8082:8080
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp=unconfined
    volumes:
      - "${MODELS_DIR}:/data/models"


volumes:
  surrealdb-data:
