[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.83"
derive_more = { version = "1.0.0", features = ["full"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
surrealdb = "2.1.4"
surrealize = "0.1.1"
thiserror = "2.0.11"
tide = "0.16.0"

tokio = { version = "1.42.0", features = ["full"] }
