[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.85"
derive_more = { version = "1.0.0", features = ["full"] }
jwt = "0.16.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.137"
surrealdb = { version = "2.1.4", features = ["http", "ml", "protocol-http"] }
surrealize = "0.1.1"
thiserror = "2.0.11"
tide = "0.16.0"
tokio = { version = "1.43.0", features = ["full"] }
