on:
  pull_request:
    paths:
      - '**.rs'
name: Clippy check

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get install -y fontconfig libfontconfig-dev
      - name: Run Clippy
        run: cd backend && cargo clippy --all-targets --all-features
