on: pull_request

name: Rustfmt

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt

      # Run rustfmt check before review to prevent invalid GitHub API calls
      - name: Run Rustfmt Check
        run: cargo fmt --all --check
        working-directory: backend

      # Run rustfmt review only if the previous check passes
      - name: Rustfmt Review
        if: success()
        uses: mbrobbel/rustfmt-check@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          mode: review

